### PR TITLE
generically set a caps property from a string

### PR DESCRIPTION
**Pull request by Zubnix**
While implementing this new feature I also encountered a bug which was introduced in my previous patch.

### CODE REVIEW

**Comment by Zubnix** [comment]
Actually the entire setCapsFromString can be removed as the generic property setting logic can now handle this. This does however introduces an API change.

**Comment by Zubnix** [comment]
Any chance for a release :wink: ?

**Comment by dturing** [comment]
sorry for the delay. i've published a release with your PR included. as this project seems quite stable to me, i've called it version 1.0  \o/

**Comment by Zubnix** [comment]
:confetti_ball: :fireworks: \o/

**Pull request merged**
