### PR TITLE
Add appsrc push & caps functionality

### PR DESCRIPTION
**Pull request by Zubnix**
Working example shows a red 'movie':

```javascript

const gstreamer = require('./build/Release/gstreamer-superficial')

const pipeline = new gstreamer.Pipeline('appsrc name=mysource is-live=true ! ' +
    'videoconvert ! video/x-raw,format=I420,width=640,height=480 !' +
    'x264enc byte-stream=true key-int-max=30 pass=pass1 tune=zerolatency threads=2 ip-factor=2 speed-preset=veryfast intra-refresh=0 qp-max=43 !' +
    'video/x-h264,profile=constrained-baseline,stream-format=byte-stream,framerate=0/1 !' +
    'openh264dec !' +
    'autovideosink');

const appsrc = pipeline.findChild('mysource')
appsrc.setCapsFromString("video/x-raw,format=RGB,width=640,height=480,bpp=24,depth=24,framerate=0/1")
pipeline.play()


function frame() {
    appsrc.push(Buffer.alloc(640 * 480 * 3, "ff0000","hex"))
    setTimeout(frame, 33)
}

frame()
```

### CODE REVIEW

**Comment by dturing** [comment]
Very nice, thank you! I'll have a look and merge shortly.

**Comment by Zubnix** [comment]
Any love? I'd like to start using it myself without relying on my own fork.

**Comment by dturing** [comment]
Sorry for the delay. I merged your contribution and released a new version on npm.

Thanks again!

**Comment by notedit** [comment]
@Zubnix   Hi,  i am running into  ` assertion 'segment->format == format' failed`  with  appsrc example

https://github.com/dturing/node-gstreamer-superficial/issues/24,  can you give me some hints?

**Pull request merged**
