### PR TITLE
relicense as MIT

### PR DESCRIPTION
**Pull request by dturing**
I'd like to re-license the project more liberally; IANAL, but i think all contributors must agree to that so @linux4kix, @dasantonym and @skaughtx0r, please state here if you're OK with that before i merge this branch into master; thanks!

### CODE REVIEW

**Comment by linux4kix** [comment]
Signed off by Jon Nettleton <jon.nettleton@gmail.com>

**Comment by dturing** [comment]
@skyrising please also sign-off here if you're OK with merging all changes off your fork and licensing under MIT.

**Comment by skaughtx0r** [comment]
I'm signing off on the license change

**Comment by dasantonym** [comment]
Of course, signing off on MIT license, too!

**Comment by skyrising** [comment]
Signing off to

**Comment by dturing** [comment]
Great, thanks guys for responding quickly and of course thanks for your contributions!

**Pull request merged**
